# Quarkus Application Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsrv
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsrv
  template:
    metadata:
      labels:
        app: appsrv
    spec:
      containers:
        - name: appsrv
          image: ghcr.io/caberger/webpack-demo:latest
          ports:
            - containerPort: 8080
#     The init container waits in a loop until postgres is available.
      initContainers:
        - name: wait
          #image: postgres:14
          image: busybox:latest
          #command: ["/bin/bash", "-c", "until pg_isready --host=postgres --user=$USER; do echo waiting for database as user $USER; sleep 2; done;"]
          command: ["ping", "postgres"]
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: password
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-admin
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: appsrv
  namespace: demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: appsrv
  selector:
    app: appsrv
  